---
# tasks file for hswong3i.postgresql_db

- name: create postgresql db
  become: yes
  become_user: postgres
  postgresql_db:
    name="{{ postgresql_db_name }}"
    encoding="{{ postgresql_db_encoding }}"
    lc_collate="{{ postgresql_db_lc_collate }}"
    lc_ctype="{{ postgresql_db_lc_ctype }}"
    template="{{ postgresql_db_template }}"
  tags: hswong3i.postgresql_db
